---
title: "class"
author: "Morgan Booker"
date: "11/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidymodels)
library(skimr)
library(fs)
```

```{r}
unzip("2018-live-poll-results-master.zip")

x <- read_csv("2018-live-poll-results-master/data/elections-poll-az02-1.csv", col_types = cols(
  .default = col_character(),
  turnout_scale = col_double(),
  turnout_score = col_double(),
  w_LV = col_double(),
  w_RV = col_double(),
  final_weight = col_double(),
  timestamp = col_datetime(format = "")
))

files <- list.files(path = "2018-live-poll-results-master/data", pattern = "*.csv", full.names = T)

tbl <- sapply(files, read_csv, simplify=FALSE) %>% 
  bind_rows(.id = "id")

my_list <- dir_ls("2018-live-poll-results-master/data/")
my_list

raw <- map_dfr(my_list, .id = "source", read_csv, col_types = cols(
  .default = col_character(),
  turnout_scale = col_double(),
  turnout_score = col_double(),
  w_LV = col_double(),
  w_RV = col_double(),
  final_weight = col_double(),
  timestamp = col_datetime(format = "")
))

skim(x)

file_delete(c("2018-live-poll-results-master.zip", "2018-live-poll-results-master/"))

```

```{r}

z <- raw %>% 
  mutate(dvote = ifelse(response == "Dem", 1, 0),
         female = ifelse(gender == "Female", 1, 0)) %>% 
  select(dvote, female, response, gender)

z %>% 
  select(response, dvote, female, gender)

mod <- glm(dvote ~ female, data = z, family = "binomial")
mod
summary(mod)

my_data <- tibble(female = c(0,0, 1))

predict(mod, newdata = my_data, type = "response")

z <- z %>% 
  mutate(prediction = predict(mod, type = "response"))
z


ggplot(z, aes(dvote, female)) +
  geom_jitter(alpha = .1)

```

